# Generated by Django 3.2.13 on 2022-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_blog',
            field=models.CharField(default='Portfolio 4 Blog', max_length=255),
        ),
    ]
